version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dacn
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: baanhemwebsitedacn
    networks:
      - app-network
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql-scripts:/docker-entrypoint-initdb.d

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
#    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--timeout=60", "--", "java", "-jar", "app.jar"]
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge